config:
  freemarker:
    enableRewrite: true
    enableLogging: false

params:
  user:
    name: "richy"
  projectName: "templator"

modelfile: "/Users/richardkoehl/workspace/templator-model/model/model.ftl"
outputfile: "/Users/richardkoehl/workspace/templator-model/out/second.ftl"