config:
  freemarker:
    enableRewrite: true
    enableLogging: false

params:
  user:
    name: "richy"
  projectName: "templator"

modelfile: "/data/model/model.ftl"
outputfile: "/data/out/out.html"